name: Push image to ECR
on:
  push:
    tags:
      - '*'
env:
  path_to_dockerfile: Dockerfile
  docker_build_dir: "."
  aws_region: "us-east-1"

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    outputs:
      tag: ${{ steps.version.outputs.next}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.aws_account_id }}:role/GHA-ECR-Full-Access
          aws-region: ${{ env.aws_region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: ${{ secrets.aws_account_id }}
          mask-password: "true"

      - name: Set next version
        id: version
        run: |

          VERSION=$(git describe --tags --abbrev=0)
          echo "Current version: $VERSION"

          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [[ "$BRANCH_NAME" == "main" ]]; then
            svu_url="https://github.com/caarlos0/svu/releases/download/v3.0.0/svu_3.0.0_linux_amd64.tar.gz"
            wget -qO- "$svu_url" | tar xvz >/dev/null 2>&1
            next="$(./svu n --always)"
          elif [[ "$BRANCH_NAME" == "staging" ]]; then
            latest_bare_tag="$(echo "$VERSION" | sed 's/-.*//g')"
            build_num="${GITHUB_RUN_NUMBER:-0}"
            next="${latest_bare_tag}-${BRANCH_NAME}.${build_num}"
          fi

          echo "Next version: $next"
          echo "next=$next" >> "$GITHUB_OUTPUT"

      - name: Build, tag, and push image to Amazon ECR
        id: build-push
        uses: docker/build-push-action@v6
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: uptime-kuma
          IMAGE_TAG: ${{ steps.version.outputs.next}}
        with:
          context: .
          file: ./docker/dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
            ${{ github.ref_name == 'main' && format('{0}/{1}:latest', env.ECR_REGISTRY, env.ECR_REPOSITORY) || '' }}
          provenance: false

      - name: Create tag
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.version.outputs.next}}',
              sha: context.sha
            })
